### ISSUE TITLE
Require.js parsing errors

### ISSUE THREAD

**Issue by jfsiii** [cramforce/streamie#1]
Accessing gh-pages/public/index.html (e.g. cramforce.streamie.org) was throwing JS errors. 
Chrome 7.0.503.0 dev: http://screencast.com/t/YmU3NTNiYTAt
FF 3.6.6: http://screencast.com/t/M2YxNDVlMDM

Fixed in FF with http://github.com/jfsiii/streamie/commit/a55e6f3cadb42016db4c800b445aaf491b6eac7c

Fixed in Chrome with http://github.com/jfsiii/streamie/commit/ed16e3fc0b64e7546d0c834e8b99cb9bf436feb0 and http://github.com/jfsiii/streamie/commit/088a3a09cb45a9883fe92f0de5bb528272fe1f92 

However, those fixes led to other issues and, while I think I'm doing the right thing, I don't want to create a stream of tickets based on a flawed approach. Will wait for this issue to be confirmed/fixed before reporting others.

**Comment by cramforce** [comment]
I think we should revert the experimental changes in the gh-pages branch. This is a side effect of the bespin thing I think

**Comment by cramforce** [comment]
Please pull from gh-pages branch and see if error persists

**Comment by jfsiii** [comment]
Deleted repo and forked anew. No issues observed in Chrome 7.0.503.0 dev. However, issues are still seen in FF 3.6.6 and 4.0b4.

The issues still seem related to require.js. http://jfsiii.streamie.org/ext/require.js and http://cramforce.streamie.org/ext/require.js are both exhibiting the odd and disconcerting behavior of returning different responses on each load. One time the response is 750 lines, the next is 850 lines, another is 1100, and so on. 

Even more strange is that the responses are "mangled", for lack of a better term. See http://pastie.org/1125912 for a representative example.

Accessing http://cramforce.streamie.org/ext/require.js via curl (and Chrome) does not show any of these inconsistencies. http://screencast.com/t/NmM2MTQwYW shows the a mangled portion of the response when http://cramforce.streamie.org/ext/require.js is entered in the location bar.

My copy of FF4b4 is brand new, with no extensions installed. FF 3.6.6 behaves the same with all extensions disabled.

I will re-apply my fixed for the unterminated multi-line comment and see if, perhaps, that is what's causing FF behave so oddly and erratically.

**Comment by antimatter15** [comment]
I'm getting the issue on chrome, and chromium. Not on wget however.

**Comment by cramforce** [comment]
Can you pull in jfsiii's fixes to see whether that works?

**Comment by cramforce** [comment]
Or by pulling the minified version. I could commit that one, but I prefer unminified code.

**Comment by cramforce** [comment]
Should be fine now

**Comment by antimatter15** [comment]
AAARRGGHHH!!!
It's happening again!!!!

FInstall&&A())NIaTU
88i3
i3ranifLene8m   \dl
8tall&&A())NIaTU
88i3
i3ranifLene8m   \dl
8tall&&A())NIaTU
88i3
id==3
id==3
id==3
id==3
id==3
id==3
id==3
idi|i{
}|i{
}|i{
}|i{
}|i{
}|i{
}|i{
}|i{
iAef\lUref\l\lUpDlUm

|i{

**Comment by cramforce** [comment]
Yeah, I've seen it too. Then it goes away again. It is probably a bug in http-proxy. Do you have time to investigate? Maybe it only occurs under heavy load. The server is getting quite a hammering :)
