### ISSUE TITLE
update http-proxy to 0.3.0 or update install instructions

### ISSUE THREAD

**Issue by Marak** [cramforce/streamie#13]
hi!

i noticed you are using node-http-proxy in your project. we just updated the api slightly (v0.3.0) and you should probably update or specify the correct install version in your instructions.

```
 npm install http-proxy@0.1.5 
```

(this is the older version which will work with your code)

if you want to update, it should just be the matter of changing a couple of lines here: http://github.com/cramforce/streamie/blob/master/lib/server.js#L198

with something like: 

```
 var proxy = new httpProxy.HttpProxy(req, res);
 proxy.proxyRequest(9000, 'localhost', req, res);
```

let me know if you need any help

**Comment by cramforce** [comment]
Upgraded. Thanks for the note!!!
