### ISSUE TITLE
node sometimes crashes

### ISSUE THREAD

**Issue by kosta** [cramforce/streamie#2]
log output:
events:12
        throw arguments[1];
                       ^
Error: ECONNRESET, Connection reset by peer
    at net:304:14
    at Client._readImpl (net:358:27)
    at IOWatcher.callback (net:454:24)
    at node.js:764:9

**Comment by cramforce** [comment]
Is this node crashing or application code? I have this sometimes when I close my laptop and then reopen it.

**Comment by kosta** [comment]
well I guess it's the application crashing. This happens during "normal operation", no laptop closing involved :)

**Comment by kosta** [comment]
This definitely seems to be related to refreshing the browser after changing client-side javascript (not node-side javascript)

**Comment by jeromeetienne** [comment]
this is not a crash, more a uncaught exception. This exception means "i tried to established a connection and the server didnt listen".

what about trapping it and handling it as normal error ?

**Comment by kosta** [comment]
Closing very old issue...
