### ISSUE TITLE
Borken navbar icons on Windows

### ISSUE THREAD

**Issue by kosta** [cramforce/streamie#20]
On Windows (tested with Chrome and Firefox), the navigation icon for settings does "direct messages", the icon for "write a tweet" does "open settings" and the icon for "direct messages" is missing (thus, you cannot write a tweet ;) ).

Sorry, got no time to investigate further. This is probably related to generating images if the glyphs are not in the font.

**Comment by badboy** [comment]
Same as #19

**Comment by cramforce** [comment]
Should be fixed

**Comment by kosta** [comment]
Is Fixed.
