### ISSUE TITLE
Did not work

### ISSUE THREAD

**Issue by arrrgrr** [cramforce/streamie#24]
Hy, its rarely fresh alpha version.
I try to use suse 11.3 linux with actual firefox from repository. I authorize the app. I see the authorize on my account. But the "Sign in with Twitter" is still present, and i will redirected still to twitter to authorize :(
The i try my nokia E65 handy, who is the reason to use your software. There i get the same Problem. I can see an error message "Cant find token" followed by cryptic stuff.

**Comment by sbrosinski** [comment]
did you:
Go to dev.twitter.com and get oAuth secrets for local.streamie.org
Edit your /etc/hosts file and map local.streamie.org to 127.0.0.1
?

**Comment by cramforce** [comment]
Are you using the offical site or are you trying to run Streamie on your own computer? The streamie web client will for now not run on mobile phones. A mobile version would be greatly appreciated.

**Comment by cramforce** [comment]
cant reproduce
