### ISSUE TITLE
@/Mentions tab

### ISSUE THREAD

**Issue by frankac2010** [cramforce/streamie#32]
I just started using streamie,everything works perfect except the @ tab/column,when i click it nothing happens,even when i refresh the tab same thing. I even tried it on another computer"both running google chrome",one is CR-48 laptop,no matter what i do,the @/mention tab won't show up,yet i can see the same tweets on the "show all"tab,is it me/a bug? any and all help would be appreciated

**Comment by cramforce** [comment]
Hey,

can you send screen shots?
The @mention tab is only a filter on your stream. It will only show mentions when there are mentions present in the all tab. I agree that this can be confusing but the streaming metaphor pretty much mandates it.

**Comment by frankac2010** [comment]
how do i send screen shots,i have one all set. i thought it was all past @mentions,not just current.

**Comment by cramforce** [comment]
The tabs are just filters on that you see in the stream. If you let streamie running forever it will be like you expected. I agree that this is weird. Do you have an idea how to fix it without leaving the paradigm of a single stream?

Upload the screens to e.g. imgur or twitpic but first send yourself an @mention so you definitely have one and see if it shows up.

**Comment by frankac2010** [comment]
test tweet worked,going to try and upload screen shot now

**Comment by frankac2010** [comment]
screen shot uploaded,i'm @franka2009,sadly i don't have any ideas to help,i'm not a developer/programmer,but i love to test new products.
