### ISSUE TITLE
Shows retweet button for direct messages and it retweets some other tweet!

### ISSUE THREAD

**Issue by senthilkumarkj** [cramforce/streamie#33]
The app shows retweet button for direct messages and when clicked it asks for confirmation. When 'yes' is clicked it does retweet but some other tweet! ( i haven't checked the code yet, so i asssume it retweets some tweet using some id available.) Interestingly, it doesn't come up in the streamie timeline but can be seen on twitter timeline.

**Comment by cramforce** [comment]
Thanks, fixed

**Comment by senthilkumarkj** [comment]
Great man!
