### ISSUE TITLE
Weird symbols in the Chrome 12

### ISSUE THREAD

**Issue by mishail** [cramforce/streamie#41]
Please take a look at http://twitpic.com/4vr8il
 I observed that both on WinXP and Win7

**Comment by cramforce** [comment]
Asked @helgri to fix. Meanwhile get yourself a system font that actually supports the full UTF8 character set. Makes web surfing overall nicer :)

**Comment by mishail** [comment]
Well, I always try to use a Deja Vu font family all the way :) 
Thanks for the best client. Streamie FTW!

**Comment by cramforce** [comment]
Should be fixed
