### ISSUE TITLE
German umlaute (äöü) and other special chars ° don't display right

### ISSUE THREAD

**Issue by alexs77** [cramforce/streamie#42]
On some tweets, like eg. https://twitter.com/Konstanz_Wetter/status/68284262981447680 , the Umlauts and other special chars aren't displayed correctly; please see screenshot on http://www.diigo.com/item/image/ytlp/iwq8

I'm using Google Chrome but have also seen this with Firefox 4 - both on Linux.

**Comment by cramforce** [comment]
This is a known issue in the Twitter API. Actually I have no idea how to fix it. The API "sometimes" encode some HTML entities. Sometimes it doesn't encode HTML. So always encoding, or always decoding, then encoding does only yield the right results in a certain percentage of cases.

**Comment by alexs77** [comment]
Okay. It's really strange, since normally HTML entities display just fine. Maybe it's something strange, which the Konstanz_Wetter account/bot does, because Umlaute from this account quite often show up wrong.

But, okay, I understand you can't do anything about it.

→ Closing Issue

**Comment by cramforce** [comment]
Twitter want to prevent XSS attacks in faulty clients. The problem is that it only does this sometimes. I've reached out to Twitter multiple times to find out when they do this.
